name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Build Docker images
        run: docker-compose build

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Test API
        run: |
          curl http://localhost:3000/tasks
